version: '2'
services:
  mysqldata:
    image: busybox
    container_name: docker-mysqldata
    volumes:
     - /var/lib/mysql
  mysql:
    build: ./mysql
    container_name: docker-mysql
    stdin_open: true
    tty: false
    ports:
      - "33060:3360"
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes_from:
      - mysqldata
  app:
    build: ./php
    container_name: docker-app
    stdin_open: true
    tty: false
    ports:
      - '8888:80'
    volumes:
      - ./src:/var/www/html
      - ./apache:/etc/apache2/sites-enabled/
    depends_on:
      - mysql
